// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

///import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
//import 'package:flutter/foundation.dart'
    //show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
//class DefaultFirebaseOptions {
//  static FirebaseOptions get currentPlatform {
//    if (kIsWeb) {
//      throw UnsupportedError(
//        'DefaultFirebaseOptions have not been configured for web - '
//        'you can reconfigure this by running the FlutterFire CLI again.',
//      );
//    }
//    switch (defaultTargetPlatform) {
//      case TargetPlatform.android:
//        return android;
//      case TargetPlatform.iOS:
//       return ios;
///      case TargetPlatform.macOS:
//        throw UnsupportedError(
//          'DefaultFirebaseOptions have not been configured for macos - '
//          'you can reconfigure this by running the FlutterFire CLI again.',
///        );
//      case TargetPlatform.windows:
//        throw UnsupportedError(
//          'DefaultFirebaseOptions have not been configured for windows - '
//          'you can reconfigure this by running the FlutterFire CLI again.',
//        );
//      case TargetPlatform.linux:
//        throw UnsupportedError(
//          'DefaultFirebaseOptions have not been configured for linux - '
//          'you can reconfigure this by running the FlutterFire CLI again.',
 //       );
//      default:
//        throw UnsupportedError(
//          'DefaultFirebaseOptions are not supported for this platform.',
//        );
//    }
//  }

//  static const FirebaseOptions android = FirebaseOptions(
//    apiKey: 'AIzaSyAwNTE4tHdmaZy_T_959FJVMJqlr3e1e_s',
//    appId: '1:653213679158:android:f5c381d230938eedffa297',
//    messagingSenderId: '653213679158',
//    projectId: 'trading-app--rs',
///    storageBucket: 'trading-app--rs.appspot.com',
 // );

//  static const FirebaseOptions ios = FirebaseOptions(
//    apiKey: 'AIzaSyAuIzCxaDrSsluFKUZMcPl9sYHaF6xfOak',
//    appId: '1:158713289746:ios:e38a442f9afd037b3f8ccb',
//    messagingSenderId: '158713289746',
//    projectId: 'trading-app-e36aa',
//    storageBucket: 'trading-app-e36aa.appspot.com',
//    iosBundleId: 'com.example.tradingAap',
//  );/
//}